@url = http://localhost:8000

# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "username": "francock",
  "password": "bananita123"
}

###

@token = {{login.response.body.token}}

### Listar médicos (con nombre de especialidad)
GET {{url}}/api/medicos
Authorization: Bearer {{token}}

### Crear médico (usar id_especialidad existente)
POST {{url}}/api/medicos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Luciana",
  "apellido": "Monardez",
  "id_especialidad": 1,
  "matricula_profesional": "MP-102030"
}

### Modificar médico
PUT {{url}}/api/medicos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Lucia",
  "apellido": "Fernandez",
  "id_especialidad": 2,
  "matricula_profesional": "MP-102030"
}

### Eliminar médico
DELETE {{url}}/api/medicos/1
Authorization: Bearer {{token}}
