@url = http://localhost:8000

### Registro
# @name registro
POST {{url}}/api/auth/registro
Content-Type: application/json

{
  "username": "francock",
  "email": "francock@example.com",
  "password": "bananita123"
}

###

# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "username": "francock",
  "password": "bananita123"
}

###

@token = {{login.response.body.token}}

### Verificar token (opcional)
GET {{url}}/api/medicos
Authorization: Bearer {{token}}
